//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IECBackend.Api.Infrastructure.Scripts.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IECBackend.Api.Infrastructure.Scripts.User.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO users (
        ///                   password_hash,
        ///                   full_name,
        ///                   email,
        ///                   phone,
        ///                   role,
        ///                   organization,
        ///                   is_active,
        ///                   created_at)
        ///VALUES (
        ///        @PasswordHash, 
        ///        @Fullname, 
        ///        @Email, 
        ///        @Phone, 
        ///        @Role, 
        ///        @Organization,
        ///        @IsActive,
        ///        @CreatedAt);.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM users WHERE id = @Id;.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS(SELECT 1 FROM users WHERE email = @Email);.
        /// </summary>
        internal static string ExistsByEmail {
            get {
                return ResourceManager.GetString("ExistsByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS(SELECT 1 FROM users WHERE id = @Id);.
        /// </summary>
        internal static string ExistsById {
            get {
                return ResourceManager.GetString("ExistsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id               AS Id,
        ///       password_hash    AS PasswordHash,
        ///       full_name        AS Fullname,
        ///       email            AS Email,
        ///       phone            AS Phone,
        ///       role             AS Role,
        ///       organization     AS Organization,
        ///       is_active        AS IsActive,
        ///       created_at       AS CreatedAt,
        ///       updated_at       AS UpdatedAt
        ///FROM users
        ///WHERE email = @Email;.
        /// </summary>
        internal static string GetByEmail {
            get {
                return ResourceManager.GetString("GetByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id               AS Id,
        ///       password_hash    AS PasswordHash,
        ///       full_name        AS Fullname,
        ///       email            AS Email,
        ///       phone            AS Phone,
        ///       role             AS Role,
        ///       organization     AS Organization,
        ///       is_active        AS IsActive,
        ///       created_at       AS CreatedAt,
        ///       updated_at       AS UpdatedAt
        ///FROM users
        ///WHERE id = @Id;.
        /// </summary>
        internal static string GetById {
            get {
                return ResourceManager.GetString("GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE users 
        ///SET password_hash   = @PasswordHash,
        ///    full_name       = @Fullname,
        ///    email           = @Email,
        ///    phone           = @Phone
        ///WHERE id = @Id;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
